preload = ~/.config/wallpapers/macchiato-windows-error.png
preload = ~/.config/wallpapers/macchiato-cloudsnight.png
wallpaper {
    monitor = 
    path=~/.config/wallpapers/macchiato-windows-error.png
}

