source = ./colors/macchiato.conf


$accent = $mauve
$accentAlpha = $mauveAlpha

$activeBorder = $lavender
$activeBorderAlpha = $lavenderAlpha

$inactiveBorder = $overlay0
$inactiveBorderAlpha = $overlay0Alpha
